header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CloudWeGo Authors

  paths:
    - '**/*.go'
    - '**/*.s'

  paths-ignore:
    - perf/cpu/calculator_mock.go
    - perf/mem/mem_mock.go

  comment: on-failure
